# This is a basic workflow to help you get started with Actions

name: Deploy Function

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  deploy-to-azure:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: 'Run pip'
        shell: bash
        run: |
          # If your function app project is not located in your repository's root
          # Please change your directory for pip in pushd
          pushd .
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: serviceavailabilityapp-test-tim-01

      - name: "Publish Build Artifact"
        uses: actions/upload-artifact@v2.1.4
        with:
          # Artifact name
          name: serviceavailabilityapp-pkg # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: /home/runner/work/_temp/*.zip 
          # The desired behavior if no files are found using the provided path.        
          if-no-files-found: warn # optional, default is warn
